### ISSUE TITLE
chore: add linting and formating checks

### ISSUE THREAD

**Issue by nohehf** [Escape-Technologies/goctopus#9]
To ensure code quality, enforce linting and formatting in a CI.
For formating use `go fmt`.
For linting, since `golint` is deprecated, maybe `go vet` or `staticcheck`.
Determine if commit hooks are needed.

**Comment by c3b5aw** [comment]
Did you heard about goreportcard? (badge that run multiple lints)

Here is an example:
https://goreportcard.com/report/github.com/Escape-Technologies/goctopus

Here is a workflow:
e.g https://github.com/Escape-Technologies/http-request-catcher/blob/main/.github/workflows/ci.yaml#L29

**Comment by nohehf** [comment]
Looks nice; what about `staticcheck`?
